export const ROOT_CONTEXT_PATH = 'http://localhost:8080/api'
export const authorizationData = () => {
  return {headers: {'Authorization': localStorage.getItem('user')}}
}

export const dataApi = (method, data) => {
  if(method === 'delete') {
    return {
      method: method,
      headers: {
        'Authorization': localStorage.getItem('user')
      }
    }
  } else {
    return {
      method: method,
      headers: {
        'Authorization': localStorage.getItem('user'),
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    }
  }
}

export const REQUEST_LOGIN_PENDING = 'REQUEST_LOGIN_PENDING';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';

export const REQUEST_LOG_OUT = 'REQUEST_LOG_OUT';

export const REQUEST_USERS_PENDING = 'REQUEST_USERS_PENDING';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';

export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED';

export const CREATE_USER_PENDING = 'CREATE_USER_PENDING';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const REQUEST_ROLES_PENDING = 'REQUEST_ROLES_PENDING';
export const REQUEST_ROLES_SUCCESS = 'REQUEST_ROLES_SUCCESS';
export const REQUEST_ROLES_FAILED = 'REQUEST_ROLES_FAILED';

export const REQUEST_MY_ORGANIZATIONS_PENDING = 'REQUEST_MY_ORGANIZATIONS_PENDING';
export const REQUEST_MY_ORGANIZATIONS_SUCCESS = 'REQUEST_MY_ORGANIZATIONS_SUCCESS';
export const REQUEST_MY_ORGANIZATIONS_FAILED = 'REQUEST_MY_ORGANIZATIONS_FAILED';

export const REQUEST_MY_ORGANIZATION_PENDING = 'REQUEST_MY_ORGANIZATION_PENDING';
export const REQUEST_MY_ORGANIZATION_SUCCESS = 'REQUEST_MY_ORGANIZATION_SUCCESS';
export const REQUEST_MY_ORGANIZATION_FAILED = 'REQUEST_MY_ORGANIZATION_FAILED';

export const CREATE_MY_ORGANIZATION_PENDING = 'CREATE_MY_ORGANIZATION_PENDING';
export const CREATE_MY_ORGANIZATION_SUCCESS = 'CREATE_MY_ORGANIZATION_SUCCESS';
export const CREATE_MY_ORGANIZATION_FAILED = 'CREATE_MY_ORGANIZATION_FAILED';

export const UPDATE_MY_ORGANIZATION_PENDING = 'UPDATE_MY_ORGANIZATION_PENDING';
export const UPDATE_MY_ORGANIZATION_SUCCESS = 'UPDATE_MY_ORGANIZATION_SUCCESS';
export const UPDATE_MY_ORGANIZATION_FAILED = 'UPDATE_MY_ORGANIZATION_FAILED';

export const DELETE_MY_ORGANIZATION_PENDING = 'DELETE_MY_ORGANIZATION_PENDING';
export const DELETE_MY_ORGANIZATION_SUCCESS = 'DELETE_MY_ORGANIZATION_SUCCESS';
export const DELETE_MY_ORGANIZATION_FAILED = 'DELETE_MY_ORGANIZATION_FAILED';

export const REQUEST_VENDORS_PENDING = 'REQUEST_VENDORS_PENDING';
export const REQUEST_VENDORS_SUCCESS = 'REQUEST_VENDORS_SUCCESS';
export const REQUEST_VENDORS_FAILED = 'REQUEST_VENDORS_FAILED';

export const REQUEST_VENDOR_PENDING = 'REQUEST_VENDOR_PENDING';
export const REQUEST_VENDOR_SUCCESS = 'REQUEST_VENDOR_SUCCESS';
export const REQUEST_VENDOR_FAILED = 'REQUEST_VENDOR_FAILED';

export const CREATE_VENDOR_PENDING = 'CREATE_VENDOR_PENDING';
export const CREATE_VENDOR_SUCCESS = 'CREATE_VENDOR_SUCCESS';
export const CREATE_VENDOR_FAILED = 'CREATE_VENDOR_FAILED';

export const UPDATE_VENDOR_PENDING = 'UPDATE_VENDOR_PENDING';
export const UPDATE_VENDOR_SUCCESS = 'UPDATE_VENDOR_SUCCESS';
export const UPDATE_VENDOR_FAILED = 'UPDATE_VENDOR_FAILED';

export const DELETE_VENDOR_PENDING = 'DELETE_VENDOR_PENDING';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_FAILED = 'DELETE_VENDOR_FAILED';

export const REQUEST_REGIONS_PENDING = 'REQUEST_REGIONS_PENDING';
export const REQUEST_REGIONS_SUCCESS = 'REQUEST_REGIONS_SUCCESS';
export const REQUEST_REGIONS_FAILED = 'REQUEST_REGIONS_FAILED';