export const ROOT_CONTEXT_PATH = 'http://localhost:8080/api'
export const authorizationData = () => {
  return {headers: {'Authorization': localStorage.getItem('user')}}
}

export const dataApi = (method, data) => {
  if(data === null || data === undefined) {
    return {
      method: method,
      headers: {
        'Authorization': localStorage.getItem('user')
      }
    }
  } else {
    return {
      method: method,
      headers: {
        'Authorization': localStorage.getItem('user'),
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    }
  }
}

export const checkStatusCode = (data, type, dispatch) => {
  if (data[0]?.statusCode !== undefined && data[0]?.statusCode !== 200) {
    throw data;
  } else {
    return dispatch({ type: type, payload: data })
  }
}

export const REQUEST_LOGIN_PENDING = 'REQUEST_LOGIN_PENDING';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';

export const REQUEST_LOG_OUT = 'REQUEST_LOG_OUT';

export const REQUEST_USERS_PENDING = 'REQUEST_USERS_PENDING';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';

export const REQUEST_USER_PENDING = 'REQUEST_USER_PENDING';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED';

export const CREATE_USER_PENDING = 'CREATE_USER_PENDING';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const REQUEST_ROLES_PENDING = 'REQUEST_ROLES_PENDING';
export const REQUEST_ROLES_SUCCESS = 'REQUEST_ROLES_SUCCESS';
export const REQUEST_ROLES_FAILED = 'REQUEST_ROLES_FAILED';

export const REQUEST_MY_ORGANIZATIONS_PENDING = 'REQUEST_MY_ORGANIZATIONS_PENDING';
export const REQUEST_MY_ORGANIZATIONS_SUCCESS = 'REQUEST_MY_ORGANIZATIONS_SUCCESS';
export const REQUEST_MY_ORGANIZATIONS_FAILED = 'REQUEST_MY_ORGANIZATIONS_FAILED';

export const REQUEST_MY_ORGANIZATION_PENDING = 'REQUEST_MY_ORGANIZATION_PENDING';
export const REQUEST_MY_ORGANIZATION_SUCCESS = 'REQUEST_MY_ORGANIZATION_SUCCESS';
export const REQUEST_MY_ORGANIZATION_FAILED = 'REQUEST_MY_ORGANIZATION_FAILED';

export const CREATE_MY_ORGANIZATION_PENDING = 'CREATE_MY_ORGANIZATION_PENDING';
export const CREATE_MY_ORGANIZATION_SUCCESS = 'CREATE_MY_ORGANIZATION_SUCCESS';
export const CREATE_MY_ORGANIZATION_FAILED = 'CREATE_MY_ORGANIZATION_FAILED';

export const UPDATE_MY_ORGANIZATION_PENDING = 'UPDATE_MY_ORGANIZATION_PENDING';
export const UPDATE_MY_ORGANIZATION_SUCCESS = 'UPDATE_MY_ORGANIZATION_SUCCESS';
export const UPDATE_MY_ORGANIZATION_FAILED = 'UPDATE_MY_ORGANIZATION_FAILED';

export const DELETE_MY_ORGANIZATION_PENDING = 'DELETE_MY_ORGANIZATION_PENDING';
export const DELETE_MY_ORGANIZATION_SUCCESS = 'DELETE_MY_ORGANIZATION_SUCCESS';
export const DELETE_MY_ORGANIZATION_FAILED = 'DELETE_MY_ORGANIZATION_FAILED';

export const REQUEST_VENDORS_PENDING = 'REQUEST_VENDORS_PENDING';
export const REQUEST_VENDORS_SUCCESS = 'REQUEST_VENDORS_SUCCESS';
export const REQUEST_VENDORS_FAILED = 'REQUEST_VENDORS_FAILED';

export const REQUEST_VENDOR_PENDING = 'REQUEST_VENDOR_PENDING';
export const REQUEST_VENDOR_SUCCESS = 'REQUEST_VENDOR_SUCCESS';
export const REQUEST_VENDOR_FAILED = 'REQUEST_VENDOR_FAILED';

export const CREATE_VENDOR_PENDING = 'CREATE_VENDOR_PENDING';
export const CREATE_VENDOR_SUCCESS = 'CREATE_VENDOR_SUCCESS';
export const CREATE_VENDOR_FAILED = 'CREATE_VENDOR_FAILED';

export const UPDATE_VENDOR_PENDING = 'UPDATE_VENDOR_PENDING';
export const UPDATE_VENDOR_SUCCESS = 'UPDATE_VENDOR_SUCCESS';
export const UPDATE_VENDOR_FAILED = 'UPDATE_VENDOR_FAILED';

export const DELETE_VENDOR_PENDING = 'DELETE_VENDOR_PENDING';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_FAILED = 'DELETE_VENDOR_FAILED';

export const REQUEST_REGIONS_PENDING = 'REQUEST_REGIONS_PENDING';
export const REQUEST_REGIONS_SUCCESS = 'REQUEST_REGIONS_SUCCESS';
export const REQUEST_REGIONS_FAILED = 'REQUEST_REGIONS_FAILED';

export const REQUEST_CATEGORIES_PENDING = 'REQUEST_CATEGORIES_PENDING';
export const REQUEST_CATEGORIES_SUCCESS = 'REQUEST_CATEGORIES_SUCCESS';
export const REQUEST_CATEGORIES_FAILED = 'REQUEST_CATEGORIES_FAILED';

export const REQUEST_CATEGORY_PENDING = 'REQUEST_CATEGORY_PENDING';
export const REQUEST_CATEGORY_SUCCESS = 'REQUEST_CATEGORY_SUCCESS';
export const REQUEST_CATEGORY_FAILED = 'REQUEST_CATEGORY_FAILED';

export const CREATE_CATEGORY_PENDING = 'CREATE_CATEGORY_PENDING';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED';

export const UPDATE_CATEGORY_PENDING = 'UPDATE_CATEGORY_PENDING';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';

export const DELETE_CATEGORY_PENDING = 'DELETE_CATEGORY_PENDING';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';

export const REQUEST_SUBCATEGORIES_PENDING = 'REQUEST_SUBCATEGORIES_PENDING';
export const REQUEST_SUBCATEGORIES_SUCCESS = 'REQUEST_SUBCATEGORIES_SUCCESS';
export const REQUEST_SUBCATEGORIES_FAILED = 'REQUEST_SUBCATEGORIES_FAILED';

export const REQUEST_SUBCATEGORY_PENDING = 'REQUEST_SUBCATEGORY_PENDING';
export const REQUEST_SUBCATEGORY_SUCCESS = 'REQUEST_SUBCATEGORY_SUCCESS';
export const REQUEST_SUBCATEGORY_FAILED = 'REQUEST_SUBCATEGORY_FAILED';

export const CREATE_SUBCATEGORY_PENDING = 'CREATE_SUBCATEGORY_PENDING';
export const CREATE_SUBCATEGORY_SUCCESS = 'CREATE_SUBCATEGORY_SUCCESS';
export const CREATE_SUBCATEGORY_FAILED = 'CREATE_SUBCATEGORY_FAILED';

export const UPDATE_SUBCATEGORY_PENDING = 'UPDATE_SUBCATEGORY_PENDING';
export const UPDATE_SUBCATEGORY_SUCCESS = 'UPDATE_SUBCATEGORY_SUCCESS';
export const UPDATE_SUBCATEGORY_FAILED = 'UPDATE_SUBCATEGORY_FAILED';

export const DELETE_SUBCATEGORY_PENDING = 'DELETE_SUBCATEGORY_PENDING';
export const DELETE_SUBCATEGORY_SUCCESS = 'DELETE_SUBCATEGORY_SUCCESS';
export const DELETE_SUBCATEGORY_FAILED = 'DELETE_SUBCATEGORY_FAILED';

export const REQUEST_SUBCATEGORIES_CATEGORY_PENDING = 'REQUEST_SUBCATEGORIES_CATEGORY_PENDING';
export const REQUEST_SUBCATEGORIES_CATEGORY_SUCCESS = 'REQUEST_SUBCATEGORIES_CATEGORY_SUCCESS';
export const REQUEST_SUBCATEGORIES_CATEGORY_FAILED = 'REQUEST_SUBCATEGORIES_CATEGORY_FAILED';

export const REQUEST_VAT_LIST_PENDING = 'REQUEST_VAT_LIST_PENDING';
export const REQUEST_VAT_LIST_SUCCESS = 'REQUEST_VAT_LIST_SUCCESS';
export const REQUEST_VAT_LIST_FAILED = 'REQUEST_VAT_LIST_FAILED';

export const REQUEST_VAT_PENDING = 'REQUEST_VAT_PENDING';
export const REQUEST_VAT_SUCCESS = 'REQUEST_VAT_SUCCESS';
export const REQUEST_VAT_FAILED = 'REQUEST_VAT_FAILED';

export const CREATE_VAT_PENDING = 'CREATE_VAT_PENDING';
export const CREATE_VAT_SUCCESS = 'CREATE_VAT_SUCCESS';
export const CREATE_VAT_FAILED = 'CREATE_VAT_FAILED';

export const UPDATE_VAT_PENDING = 'UPDATE_VAT_PENDING';
export const UPDATE_VAT_SUCCESS = 'UPDATE_VAT_SUCCESS';
export const UPDATE_VAT_FAILED = 'UPDATE_VAT_FAILED';

export const DELETE_VAT_PENDING = 'DELETE_VAT_PENDING';
export const DELETE_VAT_SUCCESS = 'DELETE_VAT_SUCCESS';
export const DELETE_VAT_FAILED = 'DELETE_VAT_FAILED';

export const REQUEST_MEASURING_UNITS_PENDING = 'REQUEST_MEASURING_UNITS_PENDING';
export const REQUEST_MEASURING_UNITS_SUCCESS = 'REQUEST_MEASURING_UNITS_SUCCESS';
export const REQUEST_MEASURING_UNITS_FAILED = 'REQUEST_MEASURING_UNITS_FAILED';

export const REQUEST_MEASURING_UNIT_PENDING = 'REQUEST_MEASURING_UNIT_PENDING';
export const REQUEST_MEASURING_UNIT_SUCCESS = 'REQUEST_MEASURING_UNIT_SUCCESS';
export const REQUEST_MEASURING_UNIT_FAILED = 'REQUEST_MEASURING_UNIT_FAILED';

export const CREATE_MEASURING_UNIT_PENDING = 'CREATE_MEASURING_UNIT_PENDING';
export const CREATE_MEASURING_UNIT_SUCCESS = 'CREATE_MEASURING_UNIT_SUCCESS';
export const CREATE_MEASURING_UNIT_FAILED = 'CREATE_MEASURING_UNIT_FAILED';

export const UPDATE_MEASURING_UNIT_PENDING = 'UPDATE_MEASURING_UNIT_PENDING';
export const UPDATE_MEASURING_UNIT_SUCCESS = 'UPDATE_MEASURING_UNIT_SUCCESS';
export const UPDATE_MEASURING_UNIT_FAILED = 'UPDATE_MEASURING_UNIT_FAILED';

export const DELETE_MEASURING_UNIT_PENDING = 'DELETE_MEASURING_UNIT_PENDING';
export const DELETE_MEASURING_UNIT_SUCCESS = 'DELETE_MEASURING_UNIT_SUCCESS';
export const DELETE_MEASURING_UNIT_FAILED = 'DELETE_MEASURING_UNIT_FAILED';

export const REQUEST_PRODUCTS_PENDING = 'REQUEST_PRODUCTS_PENDING';
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_FAILED = 'REQUEST_PRODUCTS_FAILED';

export const REQUEST_PRODUCT_PENDING = 'REQUEST_PRODUCT_PENDING';
export const REQUEST_PRODUCT_SUCCESS = 'REQUEST_PRODUCT_SUCCESS';
export const REQUEST_PRODUCT_FAILED = 'REQUEST_MEASURING_UNIT_FAILED';

export const CREATE_PRODUCT_PENDING = 'CREATE_PRODUCT_PENDING';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED';

export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';

export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';

export const RESET_DATA = 'RESET_DATA';

export const REQUEST_PRODUCT_BY_BARCODE_PENDING = 'REQUEST_PRODUCT_BY_BARCODE_PENDING';
export const REQUEST_PRODUCT_BY_BARCODE_SUCCESS = 'REQUEST_PRODUCT_BY_BARCODE_SUCCESS';
export const REQUEST_PRODUCT_BY_BARCODE_FAILED = 'REQUEST_PRODUCT_BY_BARCODE_FAILED';

export const GENERATE_PRODUCT_CODE_PENDING = 'GENERATE_PRODUCT_CODE_PENDING';
export const GENERATE_PRODUCT_CODE_SUCCESS = 'GENERATE_PRODUCT_CODE_SUCCESS';
export const GENERATE_PRODUCT_CODE_FAILED = 'GENERATE_PRODUCT_CODE_FAILED';

export const GENERATE_PLU_PENDING = 'GENERATE_PLU_PENDING';
export const GENERATE_PLU_SUCCESS = 'GENERATE_PLU_SUCCESS';
export const GENERATE_PLU_FAILED = 'GENERATE_PLU_FAILED';

export const GENERATE_BARCODE_PENDING = 'GENERATE_BARCODE_PENDING';
export const GENERATE_BARCODE_SUCCESS = 'GENERATE_BARCODE_SUCCESS';
export const GENERATE_BARCODE_FAILED = 'GENERATE_BARCODE_FAILED';

export const REQUEST_DOCUMENT_TYPES_PENDING = 'REQUEST_DOCUMENT_TYPES_PENDING';
export const REQUEST_DOCUMENT_TYPES_SUCCESS = 'REQUEST_DOCUMENT_TYPES_SUCCESS';
export const REQUEST_DOCUMENT_TYPES_FAILED = 'REQUEST_DOCUMENT_TYPES_FAILED';

export const REQUEST_DOCUMENT_TYPE_PENDING = 'REQUEST_DOCUMENT_TYPE_PENDING';
export const REQUEST_DOCUMENT_TYPE_SUCCESS = 'REQUEST_DOCUMENT_TYPE_SUCCESS';
export const REQUEST_DOCUMENT_TYPE_FAILED = 'REQUEST_DOCUMENT_TYPE_FAILED';

export const CREATE_DOCUMENT_TYPE_PENDING = 'CREATE_DOCUMENT_TYPE_PENDING';
export const CREATE_DOCUMENT_TYPE_SUCCESS = 'CREATE_DOCUMENT_TYPE_SUCCESS';
export const CREATE_DOCUMENT_TYPE_FAILED = 'CREATE_DOCUMENT_TYPE_FAILED';

export const UPDATE_DOCUMENT_TYPE_PENDING = 'UPDATE_DOCUMENT_TYPE_PENDING';
export const UPDATE_DOCUMENT_TYPE_SUCCESS = 'UPDATE_DOCUMENT_TYPE_SUCCESS';
export const UPDATE_DOCUMENT_TYPE_FAILED = 'UPDATE_DOCUMENT_TYPE_FAILED';

export const DELETE_DOCUMENT_TYPE_PENDING = 'DELETE_DOCUMENT_TYPE_PENDING';
export const DELETE_DOCUMENT_TYPE_SUCCESS = 'DELETE_DOCUMENT_TYPE_SUCCESS';
export const DELETE_DOCUMENT_TYPE_FAILED = 'DELETE_DOCUMENT_TYPE_FAILED';

export const REQUEST_INVOICES_PENDING = 'REQUEST_INVOICES_PENDING';
export const REQUEST_INVOICES_SUCCESS = 'REQUEST_INVOICES_SUCCESS';
export const REQUEST_INVOICES_FAILED = 'REQUEST_INVOICES_FAILED';

export const REQUEST_INVOICE_PENDING = 'REQUEST_INVOICE_PENDING';
export const REQUEST_INVOICE_SUCCESS = 'REQUEST_INVOICE_SUCCESS';
export const REQUEST_INVOICE_FAILED = 'REQUEST_INVOICE_FAILED';

export const CREATE_INVOICE_PENDING = 'CREATE_INVOICE_PENDING';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAILED = 'CREATE_INVOICE_FAILED';

export const UPDATE_INVOICE_PENDING = 'UPDATE_INVOICE_PENDING';
export const UPDATE_INVOICE_SUCCESS = 'UPDATE_INVOICE_SUCCESS';
export const UPDATE_INVOICE_FAILED = 'UPDATE_INVOICE_FAILED';

export const DELETE_INVOICE_PENDING = 'DELETE_INVOICE_PENDING';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAILED = 'DELETE_INVOICE_FAILED';

export const REQUEST_INVOICES_ORGANIZATIONS_PENDING = 'REQUEST_INVOICES_ORGANIZATIONS_PENDING';
export const REQUEST_INVOICES_ORGANIZATIONS_SUCCESS = 'REQUEST_INVOICES_ORGANIZATIONS_SUCCESS';
export const REQUEST_INVOICES_ORGANIZATIONS_FAILED = 'REQUEST_INVOICES_ORGANIZATIONS_FAILED';

export const REQUEST_INVOICES_VENDORS_PENDING = 'REQUEST_INVOICES_VENDORS_PENDING';
export const REQUEST_INVOICES_VENDORS_SUCCESS = 'REQUEST_INVOICES_VENDORS_SUCCESS';
export const REQUEST_INVOICES_VENDORS_FAILED = 'REQUEST_INVOICES_VENDORS_FAILED';

export const REQUEST_INVOICE_PRODUCTS_PENDING = 'REQUEST_INVOICE_PRODUCTS_PENDING';
export const REQUEST_INVOICE_PRODUCTS_SUCCESS = 'REQUEST_INVOICE_PRODUCTS_SUCCESS';
export const REQUEST_INVOICE_PRODUCTS_FAILED = 'REQUEST_INVOICE_PRODUCTS_FAILED';

export const REQUEST_INVOICE_PRODUCT_PENDING = 'REQUEST_INVOICE_PRODUCT_PENDING';
export const REQUEST_INVOICE_PRODUCT_SUCCESS = 'REQUEST_INVOICE_PRODUCT_SUCCESS';
export const REQUEST_INVOICE_PRODUCT_FAILED = 'REQUEST_INVOICE_PRODUCT_FAILED';

export const CREATE_INVOICE_PRODUCT_PENDING = 'CREATE_INVOICE_PRODUCT_PENDING';
export const CREATE_INVOICE_PRODUCT_SUCCESS = 'CREATE_INVOICE_PRODUCT_SUCCESS';
export const CREATE_INVOICE_PRODUCT_FAILED = 'CREATE_INVOICE_PRODUCT_FAILED';

export const UPDATE_INVOICE_PRODUCT_PENDING = 'UPDATE_INVOICE_PRODUCT_PENDING';
export const UPDATE_INVOICE_PRODUCT_SUCCESS = 'UPDATE_INVOICE_PRODUCT_SUCCESS';
export const UPDATE_INVOICE_PRODUCT_FAILED = 'UPDATE_INVOICE_PRODUCT_FAILED';

export const DELETE_INVOICE_PRODUCT_PENDING = 'DELETE_INVOICE_PRODUCT_PENDING';
export const DELETE_INVOICE_PRODUCT_SUCCESS = 'DELETE_INVOICE_PRODUCT_SUCCESS';
export const DELETE_INVOICE_PRODUCT_FAILED = 'DELETE_INVOICE_PRODUCT_FAILED';